-- 1 --  
SELECT TEAM_ID, LEAGUE, DIVISION, NAME 
FROM MLB_TEAM;

-- 2 --
SELECT MAX(complete_games)
AS MOST_CGS
FROM MLB_PITCHING;

-- 3 --
SELECT COUNT(*)
AS NUM_CALLUPS
FROM MLB_MASTER
WHERE DATE(DEBUT) between '2014-09-10' AND '2014-09-30';

-- 4 --
SELECT MAX(DATEDIFF(FINAL_GAME, DEBUT))
AS NUM_DAYS
FROM MLB_MASTER;

-- 5 --
SELECT AVG(OPP_BATTING_AVG)
AS AVG_OPP_BATTING_AVG
FROM MLB_PITCHING
WHERE GAMES >= 25;

-- 6 --
SELECT MAX(ATTENDANCE)
AS MOST_POPULAR,
MIN(ATTENDANCE)
AS LEAST_POPULAR,
MAX(ATTENDANCE) - MIN(ATTENDANCE)
AS DIFFERENCE
FROM MLB_TEAM;

-- 7 --
SELECT PARK
FROM MLB_TEAM
WHERE PARK LIKE '%park%'
OR PARK LIKE '%field%'
OR PARK LIKE '%stadium%'
ORDER BY PARK;

-- 8 --
SELECT COUNT(*)
AS NUM_MULTIPLE_MANAGER
FROM MLB_MANAGER
WHERE STINT > 1;

-- 9 --
SELECT MAX(STOLEN_BASES / (STOLEN_BASES + CAUGHT_STEALING))
AS SB_PERCENTAGE
FROM MLB_BATTING
WHERE STOLEN_BASES + CAUGHT_STEALING >= 20;

-- 10 --
SELECT NAME, LEAGUE, WON_WS, WON_LG, WON_DIV, WON_WC
FROM MLB_TEAM
WHERE WON_DIV = 'Y'
OR WON_WC = 'Y'
ORDER BY WON_WS DESC, WON_LG DESC, WON_DIV DESC, WON_WC DESC;