-- 1 --
SELECT name_first, name_last, shut_outs
FROM MLB_PITCHING INNER JOIN MLB_MASTER
ON MLB_PITCHING.player_id = MLB_MASTER.player_id
WHERE shut_outs>0
ORDER BY shut_outs DESC, name_last;

-- 2 --
SELECT name_first, name_last, 
(homeruns*4 + triples*3 + doubles*2 + (hits - (homeruns+triples+doubles)))
AS TOTAL_BASES
FROM MLB_MASTER INNER JOIN MLB_BATTING
ON MLB_MASTER.player_id = MLB_BATTING.player_id
WHERE name_last="Smith";

-- 3 --
SELECT MLB_TEAM.NAME, NAME_FIRST, NAME_LAST
FROM MLB_TEAM INNER JOIN mlb_manager 
ON mlb_manager.team_id = mlb_team.team_id
INNER JOIN MLB_MASTER
ON mlb_manager.player_id = mlb_master.player_id
WHERE LEAGUE="NL" AND DIVISION="C";

-- 4 -- 
SELECT THROWS, count(*)
FROM (select player_id from mlb_pitching group by player_id) as pit INNER JOIN MLB_MASTER
ON pit.PLAYER_ID = MLB_MASTER.PLAYER_ID
GROUP BY THROWS
order by throws desc;

-- 5 --
SELECT name, AVG(WEIGHT) AS AVG_PIT_WEIGHT
FROM MLB_MASTER INNER JOIN MLB_PITCHING 
ON MLB_MASTER.PLAYER_ID = MLB_PITCHING.PLAYER_ID
INNER JOIN MLB_TEAM
ON MLB_PITCHING.TEAM_ID = MLB_TEAM.TEAM_ID
GROUP BY NAME
ORDER BY AVG(WEIGHT) DESC;

-- 6 --
SELECT NAME_FIRST, NAME_LAST, HEIGHT, NAME
FROM mlb_team INNER JOIN MLB_MANAGER 
ON MLB_TEAM.TEAM_ID = MLB_MANAGER.team_id
INNER JOIN MLB_MASTER
ON mlb_manager.player_id = mlb_master.player_id
WHERE HEIGHT<70;

-- 7 --
SELECT MLB_PITCHING.PLAYER_ID, NAME_FIRST, NAME_LAST, SUM(OUTS_PITCHED)/3 AS INNINGS_PITCHED
FROM  MLB_MASTER INNER JOIN MLB_PITCHING
ON mlb_pitching.PLAYER_ID = MLB_MASTER.PLAYER_ID
INNER JOIN MLB_TEAM
ON MLB_PITCHING.TEAM_ID = MLB_TEAM.TEAM_ID
GROUP BY MLB_PITCHING.PLAYER_ID 
HAVING COUNT(*) > 1
ORDER BY INNINGS_PITCHED DESC;

-- 8 --
SELECT CONCAT(NAME_FIRST , ' ' , NAME_LAST) AS FULL_NAME, WILD_PITCHES
FROM MLB_PITCHING INNER JOIN MLB_MASTER
ON MLB_PITCHING.PLAYER_ID = mlb_master.PLAYER_ID
WHERE WILD_PITCHES >= 13 AND OUTS_PITCHED>= 500
ORDER BY WILD_PITCHES DESC;

-- 9 --
SELECT NAME_LAST, MLB_BATTING.HITS/AT_BATS AS BATTING_AVERAGE, OUTS_PITCHED/3 AS INNINGS_PITCHED
FROM MLB_BATTING INNER JOIN MLB_MASTER
ON MLB_BATTING.PLAYER_ID = MLB_MASTER.PLAYER_ID
LEFT JOIN MLB_PITCHING
ON MLB_BATTING.PLAYER_ID = MLB_PITCHING.PLAYER_ID
WHERE NAME_LAST LIKE "z%";