-- 1 --
SELECT NAME_LAST FROM
MLB_MASTER INNER JOIN MLB_BATTING
ON MLB_MASTER.PLAYER_ID = MLB_BATTING.PLAYER_ID
WHERE DOUBLES > 45;

-- 2 --
SELECT NAME_LAST FROM MLB_MASTER
WHERE PLAYER_ID IN (SELECT PLAYER_ID  
FROM MLB_BATTING
WHERE DOUBLES > 45);

-- 3 -- 
SELECT NAME_LAST, DOUBLES FROM
MLB_MASTER INNER JOIN MLB_BATTING
ON MLB_MASTER.PLAYER_ID = MLB_BATTING.PLAYER_ID
WHERE DOUBLES > 45;

-- 4 --
SELECT name, wins
FROM MLB_TEAM
WHERE WINS > (SELECT AVG(WINS) FROM MLB_TEAM)
ORDER BY WINS DESC;

-- 5 --
SELECT NAME_FIRST, NAME_LAST, HIT_BY_PITCH
FROM MLB_PITCHING INNER JOIN MLB_MASTER
ON MLB_MASTER.PLAYER_ID = MLB_PITCHING.PLAYER_ID
WHERE HIT_BY_PITCH = (SELECT MAX(HIT_BY_PITCH) FROM MLB_PITCHING);

-- 6 --
SELECT NAME_FIRST, NAME_LAST, HEIGHT, NAME
FROM MLB_MANAGER INNER JOIN MLB_MASTER
ON MLB_MANAGER.PLAYER_ID = MLB_MASTER.PLAYER_ID
INNER JOIN MLB_TEAM
ON MLB_MANAGER.TEAM_ID = MLB_TEAM.TEAM_ID
WHERE HEIGHT = (SELECT MIN(HEIGHT) FROM MLB_MANAGER INNER JOIN MLB_MASTER
ON MLB_MANAGER.PLAYER_ID = MLB_MASTER.PLAYER_ID);

-- 7 --
SELECT NAME_FIRST, NAME_LAST,
STRIKEOUTS / WALKS AS KS_PER_BB
FROM MLB_MASTER INNER JOIN MLB_PITCHING
ON MLB_MASTER.PLAYER_ID = MLB_PITCHING.PLAYER_ID
WHERE WALKS > 0 AND MLB_PITCHING.GAMES >= 25
ORDER BY KS_PER_BB DESC
LIMIT 10;

SELECT NAME_FIRST, NAME_LAST,
SUM(STRIKEOUTS) / SUM(WALKS) AS KS_PER_BB
FROM MLB_PITCHING INNER JOIN MLB_MASTER
ON MLB_MASTER.PLAYER_ID = MLB_PITCHING.PLAYER_ID
WHERE WALKS > 0 AND GAMES >= 25
GROUP BY MLB_MASTER.PLAYER_ID
ORDER BY KS_PER_BB DESC
LIMIT 10;

-- 8 --
SELECT TEAM_ID
FROM MLB_BATTING
WHERE HOMERUNS > 35
UNION
SELECT TEAM_ID
FROM MLB_BATTING
WHERE STOLEN_BASES > 40
ORDER BY TEAM_ID;

-- 9 --
SELECT PLAYER_ID
FROM MLB_PITCHING 
WHERE PLAYER_ID IN 
(SELECT PLAYER_ID FROM MLB_BATTING
WHERE MLB_BATTING.HOMERUNS > 10);

-- 10 --
CREATE VIEW mlb_national AS 
SELECT * 
FROM MLB_TEAM
WHERE LEAGUE="NL";