-- Drop Script -- 
DROP TABLE IF EXISTS MUSIC_ALBUM;
DROP TABLE IF EXISTS MUSIC_ARTIST;
DROP TABLE IF EXISTS MUSIC_LABEL;
DROP TABLE IF EXISTS MUSIC_FORMAT;

DROP TABLE IF EXISTS MUSIC_GENRE;


-- Create Table Script --
CREATE TABLE MUSIC_ARTIST (
ARTIST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
ARTIST_NAME VARCHAR(100),
ORIGIN_CITY VARCHAR(50),
GENRE_NAME ENUM("Rock", "Jazz", "Pop", "Hip Hop", "Country")
);

CREATE TABLE MUSIC_LABEL (
LABEL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
LABEL_NAME VARCHAR(75)
);

CREATE TABLE MUSIC_FORMAT (
FORMAT_ID CHAR PRIMARY KEY,
FORMAT_NAME VARCHAR(50)
);

CREATE TABLE MUSIC_ALBUM (
ALBUM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
ALBUM_NAME VARCHAR(100),
ARTIST_ID BIGINT,
RELEASE_DATE DATE,
RECORDS_SOLD INT(9),
ORIGINAL_FORMAT CHAR,
LABEL_ID BIGINT,

CONSTRAINT ARTIST_ID_FK FOREIGN KEY (ARTIST_ID) REFERENCES MUSIC_ARTIST(ARTIST_ID) ON DELETE SET NULL,
CONSTRAINT ORIGINAL_FORMAT_FK FOREIGN KEY (ORIGINAL_FORMAT) REFERENCES MUSIC_FORMAT(FORMAT_ID) ON DELETE SET NULL,
CONSTRAINT LABEL_ID_FK FOREIGN KEY (LABEL_ID) REFERENCES MUSIC_LABEL(LABEL_ID) ON DELETE SET NULL
);


-- Insert Data Script -- 
INSERT INTO MUSIC_ARTIST (ARTIST_NAME, ORIGIN_CITY, GENRE_NAME)
VALUES ('Nirvana', 'Seattle, WA', 'Rock');
INSERT INTO MUSIC_ARTIST (ARTIST_NAME, ORIGIN_CITY, GENRE_NAME)
VALUES ('Miles Davis', 'Alton, IL', 'Jazz');
INSERT INTO MUSIC_ARTIST (ARTIST_NAME, ORIGIN_CITY, GENRE_NAME)
VALUES ('Michael Jackson', 'Gary, IL', 'Pop');
INSERT INTO MUSIC_ARTIST (ARTIST_NAME, ORIGIN_CITY, GENRE_NAME)
VALUES ('Lil\' Wayne', 'New Orleans, LA', 'Hip Hop');
INSERT INTO MUSIC_ARTIST (ARTIST_NAME, ORIGIN_CITY, GENRE_NAME)
VALUES ('Willie Nelson', 'Abbott, TX', 'Country');

INSERT INTO MUSIC_LABEL (LABEL_NAME)
VALUES ('DGC Records');
INSERT INTO MUSIC_LABEL (LABEL_NAME)
VALUES ('Columbia');
INSERT INTO MUSIC_LABEL (LABEL_NAME)
VALUES ('Epic Records');
INSERT INTO MUSIC_LABEL (LABEL_NAME)
VALUES ('Cash Money');

INSERT INTO MUSIC_FORMAT (FORMAT_ID, FORMAT_NAME)
VALUES ('V', 'Vinyl');
INSERT INTO MUSIC_FORMAT (FORMAT_ID, FORMAT_NAME)
VALUES ('T', 'Cassette Tape');
INSERT INTO MUSIC_FORMAT (FORMAT_ID, FORMAT_NAME)
VALUES ('C', 'Compact Disc');
INSERT INTO MUSIC_FORMAT (FORMAT_ID, FORMAT_NAME)
VALUES ('D', 'Digital');

INSERT INTO MUSIC_ALBUM (ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID)
VALUES ('Nevermind', 
(SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME='Nirvana'), 
'1991-9-23', 30000000, 'C', 
(SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME='DGC Records')
);
INSERT INTO MUSIC_ALBUM (ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID)
VALUES ('In Utero', 
(SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME='Nirvana'), 
'1993-9-21', 15000000, 'C', 
(SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME='DGC Records')
);
INSERT INTO MUSIC_ALBUM (ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID)
VALUES ('Kind of Blue', 
(SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME='Miles Davis'), 
'1959-8-17', 4000000, 'C', 
(SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME='Columbia')
);
INSERT INTO MUSIC_ALBUM (ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID)
VALUES ('Thriller', 
(SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME='Michael Jackson'), 
'1982-11-30', 65000000, 'T', 
(SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME='Epic Records')
);
INSERT INTO MUSIC_ALBUM (ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID)
VALUES ('Bad', 
(SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME='Michael Jackson'), 
'1987-9-01', 45000000, 'T', 
(SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME='Epic Records')
);
INSERT INTO MUSIC_ALBUM (ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID)
VALUES ('Tha Carter III', 
(SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME='Lil\' Wayne'), 
'2008-6-09', 3800000, 'D', 
(SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME='Cash Money')
);
INSERT INTO MUSIC_ALBUM (ALBUM_NAME, ARTIST_ID, RELEASE_DATE, RECORDS_SOLD, ORIGINAL_FORMAT, LABEL_ID)
VALUES ('Red Headed Stranger', 
(SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME='Willie Nelson'), 
'1975-5-01', 2000000, 'V', 
(SELECT LABEL_ID FROM MUSIC_LABEL WHERE LABEL_NAME='Columbia')
);

-- SELECT * FROM  MUSIC_ARTIST;
-- SELECT * FROM  MUSIC_LABEL;
-- SELECT * FROM  MUSIC_FORMAT;
-- SELECT * FROM  MUSIC_ALBUM;


-- Modify Script --
CREATE TABLE MUSIC_GENRE (
GENRE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
GENRE_NAME VARCHAR(25)
);

INSERT INTO MUSIC_GENRE (GENRE_NAME)
SELECT DISTINCT MUSIC_ARTIST.GENRE_NAME FROM MUSIC_ARTIST
LEFT JOIN MUSIC_GENRE ON MUSIC_ARTIST.GENRE_NAME = MUSIC_GENRE.GENRE_NAME;

SELECT * FROM  MUSIC_GENRE;

ALTER TABLE MUSIC_ARTIST
ADD GENRE_ID BIGINT,
ADD CONSTRAINT GENRE_ID_FK FOREIGN KEY (GENRE_ID) REFERENCES MUSIC_GENRE(GENRE_ID) ON DELETE SET NULL;

UPDATE MUSIC_ARTIST 
INNER JOIN MUSIC_GENRE ON MUSIC_ARTIST.GENRE_NAME = MUSIC_GENRE.GENRE_NAME
SET MUSIC_ARTIST.GENRE_ID = MUSIC_GENRE.GENRE_ID;

ALTER TABLE MUSIC_ARTIST
DROP COLUMN GENRE_NAME;

SELECT * FROM  MUSIC_ARTIST;

DELETE FROM MUSIC_ALBUM 
WHERE ARTIST_ID =
(SELECT ARTIST_ID FROM MUSIC_ARTIST WHERE ARTIST_NAME="Lil\' Wayne");

-- SELECT * FROM  MUSIC_ALBUM;

DELETE FROM MUSIC_ARTIST WHERE ARTIST_NAME="Lil\' Wayne";

-- SELECT * FROM  MUSIC_ARTIST;